# Generated by Django 5.1.5 on 2025-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('page_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('display', models.BooleanField(default=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
