# Generated by Django 5.1.5 on 2025-01-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='show_on_frontend',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
