from .models import Airline  # Adjust with your actual app name

def add_airlines():
    airlines = [
        {
            'name': "American Airlines",
            'iata': "AA",
            'country': "United States",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/AA_logo.png",
        },
        {
            'name': "Delta Air Lines",
            'iata': "DL",
            'country': "United States",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/DL_logo.png",
        },
        {
            'name': "United Airlines",
            'iata': "UA",
            'country': "United States",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/UA_logo.png",
        },
        {
            'name': "British Airways",
            'iata': "BA",
            'country': "United Kingdom",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/BA_logo.png",
        },
        {
            'name': "Lufthansa",
            'iata': "LH",
            'country': "Germany",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/LH_logo.png",
        },
        {
            'name': "Air France",
            'iata': "AF",
            'country': "France",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/AF_logo.png",
        },
        {
            'name': "Emirates",
            'iata': "EK",
            'country': "United Arab Emirates",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/EK_logo.png",
        },
        {
            'name': "Qatar Airways",
            'iata': "QR",
            'country': "Qatar",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/QR_logo.png",
        },
        {
            'name': "Singapore Airlines",
            'iata': "SQ",
            'country': "Singapore",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/SQ_logo.png",
        },
        {
            'name': "Japan Airlines",
            'iata': "JL",
            'country': "Japan",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/JL_logo.png",
        },
        {
            'name': "Cathay Pacific",
            'iata': "CX",
            'country': "Hong Kong",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/CX_logo.png",
        },
        {
            'name': "KLM Royal Dutch Airlines",
            'iata': "KL",
            'country': "Netherlands",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/KL_logo.png",
        },
        {
            'name': "Alitalia",
            'iata': "AZ",
            'country': "Italy",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/AZ_logo.png",
        },
        {
            'name': "Turkish Airlines",
            'iata': "TK",
            'country': "Turkey",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/TK_logo.png",
        },
        {
            'name': "Swiss International Air Lines",
            'iata': "LX",
            'country': "Switzerland",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/LX_logo.png",
        },
        {
            'name': "Austrian Airlines",
            'iata': "OS",
            'country': "Austria",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/OS_logo.png",
        },
        {
            'name': "Finnair",
            'iata': "AY",
            'country': "Finland",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/AY_logo.png",
        },
        {
            'name': "Air Canada",
            'iata': "AC",
            'country': "Canada",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/AC_logo.png",
        },
        {
            'name': "China Southern Airlines",
            'iata': "CZ",
            'country': "China",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/CZ_logo.png",
        },
        {
            'name': "China Eastern Airlines",
            'iata': "MU",
            'country': "China",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/MU_logo.png",
        },
        {
            'name': "Aeroflot",
            'iata': "SU",
            'country': "Russia",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/SU_logo.png",
        },
        {
            'name': "LATAM Airlines",
            'iata': "LA",
            'country': "Chile",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/LA_logo.png",
        },
        {
            'name': "Aeromexico",
            'iata': "AM",
            'country': "Mexico",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/AM_logo.png",
        },
        {
            'name': "Jet Airways",
            'iata': "9W",
            'country': "India",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/9W_logo.png",
        },
        {
            'name': "IndiGo",
            'iata': "6E",
            'country': "India",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/6E_logo.png",
        },
        {
            'name': "Virgin Atlantic",
            'iata': "VS",
            'country': "United Kingdom",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/VS_logo.png",
        },
        {
            'name': "South African Airways",
            'iata': "SA",
            'country': "South Africa",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/SA_logo.png",
        },
        {
            'name': "Qantas Airways",
            'iata': "QF",
            'country': "Australia",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/QF_logo.png",
        },
        {
            'name': "Royal Jordanian Airlines",
            'iata': "RJ",
            'country': "Jordan",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/RJ_logo.png",
        },
        {
            'name': "EgyptAir",
            'iata': "MS",
            'country': "Egypt",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/MS_logo.png",
        },
        {
            'name': "Malaysia Airlines",
            'iata': "MH",
            'country': "Malaysia",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/MH_logo.png",
        },
        {
            'name': "Kenya Airways",
            'iata': "KQ",
            'country': "Kenya",
            'active': True,
            'status': "active",
            'logo': "https://path/to/logo/KQ_logo.png",
        }
    ]

    for airline in airlines:
        # Check if the airline already exists based on its IATA code
        if not Airline.objects.filter(iata=airline['iata']).exists():
            # Create a new airline record
            Airline.objects.create(
                name=airline['name'],
                iata=airline['iata'],
                country=airline['country'],
                active=airline['active'],
                status=airline['status'],
                logo=airline['logo']
            )
            print(f"Added: {airline['name']}")
        else:
            print(f"Already exists: {airline['name']}")

