# Generated by Django 5.1.5 on 2025-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking', models.BooleanField(default=False)),
                ('images', models.JSONField(blank=True, null=True)),
                ('restaurant', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('casino', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pool', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
