amenities = [
    # Economy
    [
        "Wifi",
        "Business Lounge",
        "Lie Flat Seats",
        "Priority Boarding",
        "Extra Legroom",
        "Premium Meals",
        "Noise Cancelling Headphones",
        "Checked Baggage",
        "Power Ports",
        "Amenity Kit",
        "Entertainment",
    ],
    
    # Business
    [
        "Wifi",
        "Business Lounge Access",
        "Lie Flat Seats",
        "Priority Boarding",
        "Extra Legroom",
        "Premium Meals",
        "Noise Cancelling Headphones",
        "Checked Baggage",
        "Power Ports",
        "Amenity Kit",
        "Entertainment",
        "Dedicated Check-In Counter",
        "Exclusive Lounges",
        "Enhanced Privacy",
        "Luxury Toiletries",
    ],
    
    # First Class
    [
        "Wifi",
        "Business Lounge Access",
        "Private Suite",
        "Priority Boarding",
        "Extra Legroom",
        "Premium Meals",
        "Noise Cancelling Headphones",
        "Checked Baggage",
        "Power Ports",
        "Amenity Kit",
        "Entertainment",
        "Dedicated Check-In Counter",
        "Exclusive Lounges",
        "Enhanced Privacy",
        "Luxury Toiletries",
        "Personalized Service",
        "Champagne Service",
        "Fine Dining",
    ],

    # VIP
    [
        "Wifi",
        "Private Lounge Access",
        "Personalized Concierge Service",
        "Private Jet Access",
        "Private Suite",
        "Priority Boarding",
        "Extra Legroom",
        "Premium Meals",
        "Noise Cancelling Headphones",
        "Checked Baggage",
        "Power Ports",
        "Amenity Kit",
        "Entertainment",
        "Dedicated Check-In Counter",
        "Exclusive Lounges",
        "Enhanced Privacy",
        "Luxury Toiletries",
        "Personalized Service",
        "Champagne Service",
        "Fine Dining",
        "Executive Chauffeur Service",
        "Fully Equipped Conference Rooms",
        "Access to VIP Lounges at Airports Worldwide",
    ]
]
