# Generated by Django 5.1.5 on 2025-01-27 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business Class'), ('first', 'First Class'), ('vip', 'VIP')], max_length=20)),
                ('prices', models.JSONField(verbose_name=dict)),
                ('amenities', models.JSONField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin', to='flight.flight')),
            ],
        ),
    ]
