# Generated by Django 5.1.5 on 2025-01-27 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin', '0001_initial'),
        ('flight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=25)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=10)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('jpy', 'JPY')], default='usd', max_length=20)),
                ('booking_id', models.CharField(max_length=7)),
                ('pnr', models.CharField(max_length=7)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('confirmed', 'confirmed')], default='pending', max_length=25)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('adults', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin.cabin')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
