from .models import Airport  
def add_airports():
    airports = [
        {
            'name': "Hartsfield-Jackson Atlanta International Airport",
            'city': "Atlanta",
            'country': "United States",
            'iata': "ATL",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Beijing Capital International Airport",
            'city': "Beijing",
            'country': "China",
            'iata': "PEK",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Los Angeles International Airport",
            'city': "Los Angeles",
            'country': "United States",
            'iata': "LAX",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Dubai International Airport",
            'city': "Dubai",
            'country': "United Arab Emirates",
            'iata': "DXB",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Tokyo Haneda Airport",
            'city': "Tokyo",
            'country': "Japan",
            'iata': "HND",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "London Heathrow Airport",
            'city': "London",
            'country': "United Kingdom",
            'iata': "LHR",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Paris Charles de Gaulle Airport",
            'city': "Paris",
            'country': "France",
            'iata': "CDG",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Frankfurt Airport",
            'city': "Frankfurt",
            'country': "Germany",
            'iata': "FRA",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Singapore Changi Airport",
            'city': "Singapore",
            'country': "Singapore",
            'iata': "SIN",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Hong Kong International Airport",
            'city': "Hong Kong",
            'country': "China",
            'iata': "HKG",
            'scope': "international",
            'active': True,
            'status': "active",
        },
          {
            'name': "John F. Kennedy International Airport",
            'city': "New York",
            'country': "United States",
            'iata': "JFK",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "San Francisco International Airport",
            'city': "San Francisco",
            'country': "United States",
            'iata': "SFO",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Miami International Airport",
            'city': "Miami",
            'country': "United States",
            'iata': "MIA",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Sydney Kingsford Smith Airport",
            'city': "Sydney",
            'country': "Australia",
            'iata': "SYD",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Amsterdam Schiphol Airport",
            'city': "Amsterdam",
            'country': "Netherlands",
            'iata': "AMS",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Kuala Lumpur International Airport",
            'city': "Kuala Lumpur",
            'country': "Malaysia",
            'iata': "KUL",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Rome Leonardo da Vinci International Airport",
            'city': "Rome",
            'country': "Italy",
            'iata': "FCO",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Munich Airport",
            'city': "Munich",
            'country': "Germany",
            'iata': "MUC",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Istanbul Airport",
            'city': "Istanbul",
            'country': "Turkey",
            'iata': "IST",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Shanghai Pudong International Airport",
            'city': "Shanghai",
            'country': "China",
            'iata': "PVG",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Seoul Incheon International Airport",
            'city': "Seoul",
            'country': "South Korea",
            'iata': "ICN",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Chengdu Shuangliu International Airport",
            'city': "Chengdu",
            'country': "China",
            'iata': "CTU",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Dallas/Fort Worth International Airport",
            'city': "Dallas",
            'country': "United States",
            'iata': "DFW",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Dubai Al Maktoum International Airport",
            'city': "Dubai",
            'country': "United Arab Emirates",
            'iata': "DWC",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Bangkok Suvarnabhumi Airport",
            'city': "Bangkok",
            'country': "Thailand",
            'iata': "BKK",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Jeddah King Abdulaziz International Airport",
            'city': "Jeddah",
            'country': "Saudi Arabia",
            'iata': "JED",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Zurich Airport",
            'city': "Zurich",
            'country': "Switzerland",
            'iata': "ZRH",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Vienna International Airport",
            'city': "Vienna",
            'country': "Austria",
            'iata': "VIE",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Cairo International Airport",
            'city': "Cairo",
            'country': "Egypt",
            'iata': "CAI",
            'scope': "international",
            'active': True,
            'status': "active",
        },
        {
            'name': "Cape Town International Airport",
            'city': "Cape Town",
            'country': "South Africa",
            'iata': "CPT",
            'scope': "international",
            'active': True,
            'status': "active",
        }
    ]

 

    for airport in airports:
        if not Airport.objects.filter(iata=airport['iata']).exists():
            Airport.objects.create(
                name=airport['name'],
                city=airport['city'],
                country=airport['country'],
                iata=airport['iata'],
                scope=airport['scope'],
                active=airport['active'],
                status=airport['status']
            )
            print(f"Added: {airport['name']}")
        else:
            print(f"Already exists: {airport['name']}")

